require("n0ughtchill.plugins-setup")
require("n0ughtchill.core.options")
require("n0ughtchill.core.keymaps")
require("n0ughtchill.core.colorscheme")
require("n0ughtchill.plugins.comment")
require("n0ughtchill.plugins.nvim-tree")
require("n0ughtchill.plugins.lualine")
require("n0ughtchill.plugins.telescope")
require("n0ughtchill.plugins.nvim-cmp")
require("n0ughtchill.plugins.lsp.mason")
require("n0ughtchill.plugins.lsp.lspsaga")
require("n0ughtchill.plugins.lsp.lspconfig")
require("n0ughtchill.plugins.lsp.null-ls")
require("n0ughtchill.plugins.autopairs")
require("n0ughtchill.plugins.treesitter")
require("n0ughtchill.plugins.gitsigns")
require("n0ughtchill.plugins.catppuccin")
vim.opt.shell = "bin/bash"
